### ISSUE TITLE
BroadcastActivity crashes immediately when resolution is not supported

### ISSUE THREAD

**Issue by Minibrams** [sea-shanty-2/envue#19]
The BroadcastActivty, when started from the InitializeBroadcastActivity, crashes immediately due to what seems like unsupported resolution. On branch begin-stream-dialog. See the following log dump for details: 

`2019-04-10 14:28:25.175 605-1321/? E/algorithm_common: SREALGO_CONFIG sre parseParameterpara number is error 792
2019-04-10 14:28:25.175 605-1321/? E/algorithm_common: SREALGO_CONFIG sre parseParameterpara number is error 792
2019-04-10 14:28:25.187 714-24201/? E/Camera2-Parameters: set: Requested picture size 640 x 360 is not supported
2019-04-10 14:28:25.189 10999-10999/dk.cs.aau.envue E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dk.cs.aau.envue, PID: 10999
    java.lang.RuntimeException: Unable to start activity ComponentInfo{dk.cs.aau.envue/dk.cs.aau.envue.BroadcastActivity}: java.lang.RuntimeException: setParameters failed
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3300)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
     Caused by: java.lang.RuntimeException: setParameters failed
        at android.hardware.Camera.native_setParameters(Native Method)
        at android.hardware.Camera.setParameters(Camera.java:2149)
        at net.ossrs.yasea.SrsCameraView.startCamera(SrsCameraView.java:314)
        at net.ossrs.yasea.SrsPublisher.startCamera(SrsPublisher.java:63)
        at dk.cs.aau.envue.BroadcastActivity.onCreate(BroadcastActivity.kt:151)
        at android.app.Activity.performCreate(Activity.java:7436)
        at android.app.Activity.performCreate(Activity.java:7426)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:7470) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958) `

**Comment by bruunand** [comment]
Fix: query the camera for available resolutions and pick a suitable one (might want to implement a dialog in the future)

**Comment by Minibrams** [comment]
Sub-optimal solution using deprecated Camera class and the same resolution for preview and output implemented in 282c6aa1722eaaea169fcfbfdcae9475671e1c87. 

May require future work on choosing the optimal output size from the StreamConfigurationMap class.
